### ISSUE TITLE
More install method for lower version tizen

### ISSUE THREAD

**Issue by h26v** [reisxd/TizenBrew#10]
My TV has Tizenbrowser 2.4, please add installation method for lower versions

**Comment by DeadSomeOne** [comment]
Minimum required tizen version for tizenbrew is 3, henco no installation method for 2.4 or lower

**Comment by reisxd** [comment]
Tizen Web Services does not exist under Tizen 3.0.

**Comment by AndGuz** [comment]
hi, i have a 2015 samsung tv and i wasnt able to install tizenbrew via any form, is there a way to install it on old tvs?

**Comment by reisxd** [comment]
> hi, i have a 2015 samsung tv and i wasnt able to install tizenbrew via any form, is there a way to install it on old tvs?

See the answer above.

**Comment by InvisibleRain** [comment]
Managed install [TizenTube-Legacy](https://github.com/ThowZzy/TizenTube-Legacy) on Tizen 2.4. You might wanna give it a try
