### ISSUE TITLE
Add request : Moonlight (Game Streaming)

### ISSUE THREAD

**Issue by LeGeRyChEeSe** [reisxd/TizenBrew#12]
I would like to suggest you to add the service Moonlight so we can stream any game content from any PC hosted in local network for example, directly on the TV without paying any subscription to Nvidia GEForce Now for exemple.

**Comment by cremor** [comment]
There is https://github.com/mariotaku/moonlight-tv
It claims to be easy to port to other OSes. Maybe that includes Tizen?

**Comment by reisxd** [comment]
https://github.com/OneLiberty/moonlight-chrome-tizen already exists.

**Comment by LeGeRyChEeSe** [comment]
> https://github.com/OneLiberty/moonlight-chrome-tizen already exists.

Thank you i didn’t know i could do that !
