### ISSUE TITLE
2024 TVs

### ISSUE THREAD

**Issue by m1ckyb** [reisxd/TizenBrew#14]
Hey, 

Has anyone had any luck installing this on a 2024 TV (Version 8 i beleive)

Tried installing the documented way, it failed with `install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>`

Saw a method of extracting the `author-signature.xml` & `signature1.xml` files modifying them with your keys to install, buiit that also failed to install

I've tried compiling it for version 8 through tizen studio, it's no good and complains about needing version 3

Even tried the USB install method, but that also failed with `app.tmg, The aplication cannot be installed because the validity period has expired. [-6]` 

Any help / workarounds would be greatly appricated

**Comment by reisxd** [comment]
See the new release.

**Comment by m1ckyb** [comment]
Just an update still cannot install via the command line but the USB method works..

The update app loads but does nothing at all, I'm guessing it's supposed to install Tizen brew for me..

Tizen brew installs fine and runs perfectly via USB.

So thanks..
