### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by MinaMalaak** [reisxd/TizenBrew#15]
Hello,

whenever i press on the icon the app open and then close again fast  ( crash ) 
![d24db22f-e3e4-4c9c-8276-a417e8905148](https://github.com/reisxd/TizenBrew/assets/173768867/172ae1e4-5ca3-49cb-94f1-07dd86109e3f)

it didnt give me the time to press the green button or anything
can you please help !
![d24db22f-e3e4-4c9c-8276-a417e8905148](https://github.com/reisxd/TizenBrew/assets/173768867/eb065141-1a88-446c-b36d-751a4e162a6e)

**Comment by diogodiogo2** [comment]
The same happened to me, just restart the tv by holding the power button
