### ISSUE TITLE
problem compilation for TQ55QN85D

### ISSUE THREAD

**Issue by freeman5** [reisxd/TizenBrew#21]
Hello,

I try since yesterday to compile and lunch TizenBrew on my TV with no succes, i have this error : 

![image](https://github.com/user-attachments/assets/17627760-3cb7-4684-9c31-78ebc6d7859c)

please can you help me ?

Thank you.

**Comment by reisxd** [comment]
You did not install the TV Extension SDK.


If you get configuration errors, go into `JSON key should begin with "` errors and replace those files contents with just `{}`.

**Comment by freeman5** [comment]
![image](https://github.com/user-attachments/assets/af4793fd-f6dc-4e1c-a910-a794e024967d)
![image](https://github.com/user-attachments/assets/9b6a6939-ff9f-4ae0-b387-6558a0925a93)
![image](https://github.com/user-attachments/assets/2ab385be-1f12-4437-b3c8-80e4d3971a5f)

i dont understand normaly all is correctly installed, what is your version of tizen studio plz ?
