### ISSUE TITLE
problem compilation for TQ55QN85D

### ISSUE THREAD

**Issue by freeman5** [reisxd/TizenBrew#22]
Hello, 

![image](https://github.com/user-attachments/assets/a7fbb800-c2f3-4e86-9272-e96a70c3057e)
![image](https://github.com/user-attachments/assets/a09b0ffe-4fa9-4bfb-94a9-2cb19e76b291)
![image](https://github.com/user-attachments/assets/9b6a6939-ff9f-4ae0-b387-6558a0925a93)
![image](https://github.com/user-attachments/assets/2ab385be-1f12-4437-b3c8-80e4d3971a5f)

i dont understand normaly all is correctly installed, what is your version of tizen studio plz ? When i import your project i dont have tyzen web project :/ can you tell me what is your mirror in package manager and wich package you installed ? thank you

**Comment by bartzz** [comment]
I'm having the same issue. The project can't be imported as "Tyzen Project" and I don't have "Tyzen Web Project" anywhere on the list. Will try to solve it by installing more extensions, does anyone have any clues? Thank you.

**Comment by freeman5** [comment]
I have installed all sdk tool and 8.0 tizen tool and all extension sdk extra but i dont have import as tyzen web project, and same error, what is your version of tyzen studio ?
