### ISSUE TITLE
V1.3.3 - Tizenbrew is stuck on starting the service

### ISSUE THREAD

**Issue by ssdhage** [reisxd/TizenBrew#24]
With today's latest update 1.3.3, Tizen Brew is stuck in a loop trying to start the service. It keeps going from "starting service" to "service started" and back to "starting service." This issue prevents us from exiting Tizen Brew, and we have to use a long press on the return button to terminate it. I tried disabling auto-launch, but the issue still persists. It was working fine with version 1.3.1.

**Comment by reisxd** [comment]
Reinstall the layesy update.

**Comment by ssdhage** [comment]
This was an issue with version 1.3.3, and reinstalling didn’t help. So, I uninstalled it, waited for the next release, and it seems that version 1.3.5 solved the problem, and I’m now able to use it. I’d suggest uninstalling TB, restarting the TV, may be wait for a day and then trying the installation again.

**Comment by testuser7** [comment]
Previously I had `v1.3.2` installed. Before update old version was manually uninstalled.
Is there any way to check actually installed version?
