### ISSUE TITLE
Invalid certificate chain with certificate in signature

### ISSUE THREAD

**Issue by scharf9210** [reisxd/TizenBrew#26]
I have a Neo QLED 8K QN800D Tizen OS™ Smart TV (2024), and I've tried various methods to install TizenBrew, but it has failed every time. When using TizenBrew Updater, I get the following error:

Could not install app. Reason: app_id[xvvl3S1bvH.TizenBrewStandalone] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>

I also tried using a USB drive, but after recognizing it, the installation does not proceed automatically.

I attempted to rebuild TizenBrew, but the process gets stuck during the run stage and doesn't proceed any further. I'm not an expert in this field, so I’m unable to proceed any further.

up to date, audited 269 packages in 3s

24 packages are looking for funding
  run `npm fund` for details

1 high severity vulnerability

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

ncc: Version 0.38.1
ncc: Compiling file index.js into CJS
1471kB  dist\index.js
1471kB  [798ms] - ncc 0.38.1

Errors(74 items)
JSON key should begin with ~~
JSON should begin with ~~
...

Warnings (100 of 4228 items)
~~ is defined but never used.	
...

**Comment by SebastienBenazet** [comment]
I'm have the same issue trying to install TizenBrew on my Samsung QE65 using the command line :
![image](https://github.com/user-attachments/assets/4fd261b5-f897-4b7f-88db-c47eefa2a8d1)

I recreated a new certificate but it didn't change anything.

**Comment by emeraldtip** [comment]
Same issue here, installing through commandline produces this:
```
Transferring the package...
Transferred the package: G:\tizen-studio\tools\ide\bin\TizenBrewStandalone-New.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install xvvl3S1bvH.TizenBrewStandalone
package_path /home/owner/share/tmp/sdk_tools/tmp/TizenBrewStandalone-New.wgt
app_id[xvvl3S1bvH.TizenBrewStandalone] install start
app_id[xvvl3S1bvH.TizenBrewStandalone] installing[9]
app_id[xvvl3S1bvH.TizenBrewStandalone] installing[19]
app_id[xvvl3S1bvH.TizenBrewStandalone] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [1021]ms
Failed to install Tizen application.
Total time: 00:00:02.804
```

**Comment by GlitchDev1** [comment]
I have exactly the same issue as emeraltip.

**Comment by neonmik** [comment]
Apparently you should be using "TizenBrewStandalone-Old.wgt" to install if your TV isn't running TizenOS 8.0. As per #17.

**Comment by reisxd** [comment]
I'll be closing this due to the documentation mentioning that you have to rebuild TizenBrew for Tizen 8 and above. You can ask about building problems in our Discord server.
