### ISSUE TITLE
Crashlooping

### ISSUE THREAD

**Issue by Reviloje** [reisxd/TizenBrew#29]
Just this:

https://github.com/user-attachments/assets/7bb10183-7291-4099-8172-9d601a2b934a

Tried settings n stuff but I only got into tizentube once but was never able to replicate this. Running a (smart) odissey G7 4k 28" with newest tizen version.

**Comment by rawen90** [comment]
I have the same problem on Q80A from 2020 with TizenBrew ver. 1.3.5, ver. 1.3.4 is working ok

**Comment by georgeoshardo** [comment]
Getting the same issue 

> > I have the same problem on Q80A from 2020 with TizenBrew ver. 1.3.5, ver. 1.3.4 is working ok
> 
> I have the exact same thing on version 1.3.4 too :,(

I think that's because v1.3.5 and v1.3.4 are the exact same binary, see my issue #30

**Comment by kienhg96** [comment]
I have the same thing as well, but it does not loop again. My TV has Tizen 6.

**Comment by Reviloje** [comment]
So you suggest I try 1.3.2?

**Comment by rawen90** [comment]
I tested all version from 1.3.1, all crashlooping when install with windows updated methods, I finally got it working back when I install standalone.wgt and updater.wgt, both 1.3.4 ver. with sdb method

**Comment by rawen90** [comment]
> I tested all version from 1.3.1, all crashlooping when install with windows updater method, I finally got it working back when I install standalone.wgt and updater.wgt, both 1.3.4 ver. with sdb method

I tested ver. 1.3.5 with sdb method but it crashlooping too

**Comment by Reviloje** [comment]
> I tested all version from 1.3.1, all crashlooping when install with windows updated methods, I finally got it working back when I install standalone.wgt and updater.wgt, both 1.3.4 ver. with sdb method

What's the "sbd" method?

**Comment by rawen90** [comment]
> > I tested all version from 1.3.1, all crashlooping when install with windows updated methods, I finally got it working back when I install standalone.wgt and updater.wgt, both 1.3.4 ver. with sdb method
> 
> What's the "sbd" method?

https://github.com/reisxd/TizenBrew/blob/main/docs/README.md#using-the-command-line

**Comment by Reviloje** [comment]
when creating a certificate profile my browser downt open so i cant install it like that.

**Comment by Xoma163** [comment]
Same on Q60A 1.3.5

**Comment by panda7789** [comment]
Updater always picks latest release version on GitHub, so maybe that's why over updater also older versions fails.

**Comment by reisxd** [comment]
This should be fixed with the latest release.
