### ISSUE TITLE
Incorrect binary versions being released?

### ISSUE THREAD

**Issue by georgeoshardo** [reisxd/TizenBrew#30]
I am encountering the crash-loop issue in issue #29, and tried to downgrade to  v1.3.4 but still had the same issue. I noticed that 
tizenbrew-updater-linux-x64 has the same sha265sum for v1.3.5, v1.3.4, v.1.3.3 are all identical (6b21d7e631985de8ed36f51df819238fe4a68fe1e4d3cc3ab92c12aa91a43ff4). Things are different when I get to v1.3.2 though (d2064e6f494b9f686f1d13d8ac0ea24bc598055c8419492269b8601ec53fdbde).

**Comment by reisxd** [comment]
Updater fetches the latest release `TizenBrewStandalone-*.wgt` and installs it. Updater doesn't need to be different because its an entirely different application from TizenBrew.

**Comment by georgeoshardo** [comment]
So how is it possible to install an older build?

**Comment by reisxd** [comment]
Use Tizen CLI.
