### ISSUE TITLE
There are apps for Mac, but they won't start

### ISSUE THREAD

**Issue by timirey** [reisxd/TizenBrew#32]
How to start these Mac files? They don't even have any extension

**Comment by reisxd** [comment]
They're for M series Macs and you can run them in the terminal.

**Comment by reisxd** [comment]
Most likely your Mac is not  ARM64 (M-Series).

**Comment by steynvanesveld** [comment]
Are there any updates on this issue, it is marked as closed but the question was not answered. Following the steps in the README it simply states "Run the TizenBrew Updater and follow the instructions." but how are you supposed to run a binary?
