### ISSUE TITLE
connect ECONNREFUSED

### ISSUE THREAD

**Issue by VytautasMartusevicius** [reisxd/TizenBrew#33]
I try installing tizenbrew with Using TizenBrew Updater.
I enter developer mode in my tv. 
I change the ip address to be the same as pc.
Launch tizenbrew updater -> open localhost -> enter ip address -> click connect, but I get error:
Service started.
Please open up http://localhost:8083 in your browser.
(node:166563) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `tizenbrew-updater-linux-x64 --trace-deprecation ...` to show where the warning was created)
ADB connection error. Error: connect ECONNREFUSED MY_IP:26101 (MY_IP changed to text instead of real one)
ADB connection closed.

After this I don't know what to do.

My tv is Samsung UE55CU7172UXXH, UHD, 55 "

**Comment by reisxd** [comment]
Your TVs IP should be the local IPv4 address and your PCs IP should also be the same. Don't forget to reboot your TV by holding the power button till you see the Samsung logo or the bouncing home.
