### ISSUE TITLE
need help in starting tizenbrew

### ISSUE THREAD

**Issue by partyofocelots** [reisxd/TizenBrew#4]
i wanted to temporarily install tizenbrew by inserting the usb with the usb demo. i enabled dev mode and connected to the host pc ip, but nothing happened. the app didn't appear at all

i'm using ubuntu 22.04.4 lts if this helps

**Comment by ansh5671** [comment]
that will be nice if you make a video about how to install tizenbrew

**Comment by vintoware** [comment]
@partyofocelots how did you format your flash drive? I formatted mine as FAT32 and it went smooth - after powering on the TV the app was installed and I saw the notification about it.

**Comment by doblejote** [comment]
saludos, o sea que coloca la usb con el TV apagado y al encender, el sistema instala la app?, voy a probar, alguien tiene un paso a paso? Gracias

**Comment by ansh5671** [comment]
No I didn't turn off the TV I just put USB in while it was on and it shows
me empty drive.

**Comment by ansh5671** [comment]
I installed it but it keep showing error; couldn't connect to the server after 3 attempts. I changed the host IP to 127.0.0.1

**Comment by ansh5671** [comment]
You can't launch modules while service hasn't connected yet. How to fix this issue ?

**Comment by goodness-from-me** [comment]
@ansh5671 try rebooting the TV - hold the power button on your remote for about 4 seconds - TV will shutdown completely, then power it on and try again.

**Comment by ansh5671** [comment]
It worked. Thanks
