### ISSUE TITLE
Autolaunch not working

### ISSUE THREAD

**Issue by TheKackboon** [reisxd/TizenBrew#60]
My Samsung GQ65Q60T does not autolaunch TizenTube, although it used to work on 1.3.4. Every time I hard restart the TV, force close the app or leave the TV on standby over night, the app freezes on the module menu where it used to launch TizenTube.
I used two install methods, the one over the internet browser (easy) and the one Updater one. Initially on 1.3.4 I also used the Installer methods via internet browser.

**Comment by Yiri-cz** [comment]
Same here. I just left TV standby over night and another day TizenTube hasn't launched anymore. QE55Q80T

**Comment by Yiri-cz** [comment]
OK, I reinstalled it and left developer mode ON and it works so far. Try developer mode ON.

**Comment by TheKackboon** [comment]
My developer mode is always on. As far as I know, the app isn’t even supposed to work if the developer mode is not on.

**Comment by Yiri-cz** [comment]
Do you log in to your YT account in the tizentube app?

**Comment by TheKackboon** [comment]
Yes

**Comment by mattegoghero** [comment]
Hi, I have installed TizenTube on my UE55RRU7170UXZT that should be running Tizen 5, when I open the TizenBrew app it closes and reopens automatically right after and it gets to the app homescreen, but then TizenTube doesn't get autolaunched despite selecting it in the autolaunch settings.
