### ISSUE TITLE
Error compiling from source

### ISSUE THREAD

**Issue by Ste-Mich** [reisxd/TizenBrew#61]
I followed the tutorial for Rebuilding TizenBrew according to all of the instructions.

after building the project with npm I get a lot of errors in the IDE:
![error2](https://github.com/user-attachments/assets/e1acb56e-aefd-4d27-ad76-efddab8d5fa7)

The output of 'npm i':
![image](https://github.com/user-attachments/assets/fa884406-c535-47de-b917-0e4f0db170e5)

The output of 'npx @vercel/ncc build service.js':
![image](https://github.com/user-attachments/assets/ca325ff7-1379-4c35-9370-7140eebd1066)

the step after - 'Run As > Tizen Web Application' does not work either. I get a compilation error:
![ERROR1](https://github.com/user-attachments/assets/2a38e95d-e174-49f3-a83e-ed05e3bccf53)

I tried both cloning with git (which gave me just the errors, not the null pointer, but some other) and downloading the source code from the release page.

My 'npm --version' is 10.9.0. I'am on Windows, but can try Linux, if it would help.

Thanks in advance

**Comment by reisxd** [comment]
See the new guide.
