### ISSUE TITLE
Question regarding documentation for Rebuilding TizenBrew

### ISSUE THREAD

**Issue by Ste-Mich** [reisxd/TizenBrew#62]
I have two questions regarding the Rebuilding TizenBrew section on [here](https://tizentube.vercel.app/documentation#/./docs/README) and [here](https://github.com/reisxd/TizenBrew/blob/main/docs/README.md).

First one is an inconsequential typo, which just made me unsure whether I have the correct plugins installed inside the IDE. Inside the second step there is written: 'File > Import > Tizen > Tizen Web Project'. Inside the Tizen IDE there is only an import for 'Tizen Project'
![image](https://github.com/user-attachments/assets/d3adf577-e6b0-47d7-a5e4-59d6ebc44adf)

Second one happened to me after 'Run As > Tizen Web Application' (step 6). There are two pop-ups that show up:
![Untitlearstd](https://github.com/user-attachments/assets/0afb38c1-283c-4027-88fc-5d85397940b5)
![Untitledsafda](https://github.com/user-attachments/assets/e57d0ce9-62d2-473c-8c83-c70a7762c43f)

I ignored both of them, which I presume is correct. I think it would be good to mention these in the documentation for anybody else unfamiliar with Tizen IDE.

Should I edit the docs and open a PR? I would like to contribute

**Comment by reisxd** [comment]
See the new guide.
