### ISSUE TITLE
Video jump/freezes during watching some videos

### ISSUE THREAD

**Issue by socheck** [reisxd/TizenBrew#65]
Hello, there is a problem while watching some videos on tizenbrew youtube - specific channels. While watching it, there comes jump freezes of video while audio is going well. There is no buffering, just 'frog jumps'. I think it depends on specific frame rate used by a creator. If there is a posibility I can collect logs and deliver yotube video example.

**Comment by reisxd** [comment]
Not an issue with TizenBrew. Use the blue button in TizenTube and scroll all the way down and select the last option.
