### ISSUE TITLE
Cannot launch any modules.

### ISSUE THREAD

**Issue by bolabola6789** [reisxd/TizenBrew#7]
I couldn't get any any modules to launch, and I also have no idea if they were installed.
TizenBrew app can start normally, at the module launcher the status at the top right says "Service is already running"
At the module launcher the status just says "Status" and nothing else. There is a button to Add but other than that it's blank (there is a blue highlight)
It can be installed but module launcher says "Undefined", and if auto launch is enable it would just say "couldn't find modules"

**Comment by bolabola6789** [comment]
I give up. I ended up getting the chromecast with google tv instead.

**Comment by bolabola6789** [comment]
Decided to retry after someone else I recommended succeeded. Version used is v1.2.0. Behavior is a bit different this time. The TizenBrew app is installed normally, host PC IP is set to 127.0.0.1
![DSC_0163](https://github.com/reisxd/TizenBrew/assets/105188534/03829fa1-9e34-47c9-a111-b8949ab80860)
![DSC_0164](https://github.com/reisxd/TizenBrew/assets/105188534/8f57816c-c5c5-4280-86cc-b6380f42076e)
Now everytime I open the app it will closes and reopen itself, greeting me with cannot connect to 127.0.0.1 but on the top right corner it says connected? Modules won't properly install, as shown in the photo as "undefined" and will do nothing when pressed OK.

**Comment by reisxd** [comment]
The modules did load, which means that the error is only cosmetic and won't affect TizenBrew. The module you've added is not a TizenBrew module, which is why nothing happens.

**Comment by bolabola6789** [comment]
> The modules did load, which means that the error is only cosmetic and won't affect TizenBrew. The module you've added is not a TizenBrew module, which is why nothing happens.

Oh wow, I realized after I read this comment that the module name must be @foxreis/tizentube

Gosh how dumb I was. Thank you so much
