### ISSUE TITLE
Using TizenBrew Installer: Invalid certificate chain with certificate in signature.:<-3>

### ISSUE THREAD

**Issue by vc-kpi** [reisxd/TizenBrew#70]
![image](https://github.com/user-attachments/assets/7dbab03e-8139-42c5-9d49-a0ac1d6e6625)

`C:\tizen-studio\tools>tizen install -n TizenBrewStandalone.wgt
Transferring the package...
Transferred the package: C:\tizen-studio\tools\TizenBrewStandalone.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install xvvl3S1bvH.TizenBrewStandalone
package_path /home/owner/share/tmp/sdk_tools/tmp/TizenBrewStandalone.wgt
app_id[xvvl3S1bvH.TizenBrewStandalone] install start
app_id[xvvl3S1bvH.TizenBrewStandalone] installing[10]
app_id[xvvl3S1bvH.TizenBrewStandalone] installing[12]
app_id[xvvl3S1bvH.TizenBrewStandalone] installing[15]
app_id[xvvl3S1bvH.TizenBrewStandalone] installing[17]
app_id[xvvl3S1bvH.TizenBrewStandalone] installing[20]
app_id[xvvl3S1bvH.TizenBrewStandalone] installing[22]
app_id[xvvl3S1bvH.TizenBrewStandalone] installing[25]
app_id[xvvl3S1bvH.TizenBrewStandalone] installing[27]
app_id[xvvl3S1bvH.TizenBrewStandalone] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [863]ms
Failed to install Tizen application.
Total time: 00:00:02.196`

**Comment by mrdbooker** [comment]
I had the same issue. Had to also make a certificate (distribution - partner type - not sure if that is important). Then had to build the app myself following [Rebuilding TizenBrew part in the instructions](https://github.com/reisxd/TizenBrew/tree/main/docs). 

After that had some further issues with TizenBrew app saying it needs to connect to the server or something. This was resolved by disabling auto start of the modules in TizenBrew settings.

**Comment by DrowningElysium** [comment]
![image](https://github.com/user-attachments/assets/89f436b6-4ed5-45b4-a655-dd0a9ae45ad7)
I am having the same issue here. Created a certificate, marked it as default and then followed the terminal steps as you can see in the screenshot. 

Not sure what went wrong as the installation is also saying invalid certificate. Could anyone point me in the right direction?

**Comment by reisxd** [comment]
You must rebuild the app with a Samsung certificate, not a Tizen certificate. It should also be set to the "New" type.

**Comment by DrowningElysium** [comment]
> You must rebuild the app with a Samsung certificate, not a Tizen certificate. It should also be set to the "New" type.

There is no option when you create one to choose either. This screen is nowhere to be found https://developer.samsung.com/media/2128/certificateprofile3.png

**Comment by DrowningElysium** [comment]
Found the issue for other people following this thread. When you install the certificate manager through the package manager. Go to the "Extension SDK" tab. Almost at the bottom you will find "Samsung Certificate Extension". You need to install this one.

![image](https://github.com/user-attachments/assets/b8167f02-e3ac-45dc-b1e2-3c3711387e4c)
