### ISSUE TITLE
TizenBrew Modules screen empty

### ISSUE THREAD

**Issue by srafferty73** [reisxd/TizenBrew#72]
First off, thanks for this. It works mostly and I'm happy.
However, sometimes when I start it up, it shows the TizenBrew Modules stage briefly then back to Samsung then back to TB Modules. Normally, I can start the app as the only box option. All good. But occasionally I get a completely empty box and no amount of clicking or accessing the settings makes anything happen. Settings takes me back to Add NPM/Github Module and the only thing I know to try is to enter your @foxreis/tizentube in the Github box. But then I end up back on the empty box screen again.

I've tried to reinstall app, but no joy. If I knew how to hard reset the TV , maybe that'd work. However I think a power down may fix this?

**Comment by srafferty73** [comment]
So, a solution I've found to this is to uninstall/reinstall the entire app on the TV and it brings back the tizentube box when I start the app up again.

**Comment by MBurzynski** [comment]
I have the same problem but reinstalling the app didn't help :( Only empty box is displayed and when I try to click it I get pop-up with error "You can't launch modules while the service hasn't connected to the app yet". And no matter how long I wait or how many times I close and open the app, I still have this empty box.
![20241108_172511](https://github.com/user-attachments/assets/e6c6c490-6e0a-497c-aebd-ffe2f49feb42)

**Comment by reisxd** [comment]
Check the new release.

**Comment by MBurzynski** [comment]
Thanks for the fast reply, works great on the new release
