### ISSUE TITLE
2023 TV with Tizen 7 updated to OneUI, broke Tizenbrew and can't reinstall. 

### ISSUE THREAD

**Issue by Nebarik** [reisxd/TizenBrew#74]
After updating the tv with the new OneUI update. The tizenbrew app stopped working. It then uninstalled itself a short time later. 

Attempted to reinstall it via the updater method, get errors either referring to a certificate error or simple failed to install. 
Attemped to install via the usb demo method. Gave the error that the validatory period has ended.

**Comment by reisxd** [comment]
You'll have to rebuild the application to install it back.

**Comment by Nebarik** [comment]
Thanks, I did that and it worked. But holy crap was that a difficult and confusing process compared to the updater. I have dev experience at least, I dread the comments you're going to get from less experienced users.
