### ISSUE TITLE
Request to re-add the TizenBrewStandalone-New.wgt release (to allow manually replacing certificate)

### ISSUE THREAD

**Issue by MattBayliss** [reisxd/TizenBrew#78]
I'd like to request the `TizenBrewStandalone-New.wgt` release be re-added, because rather than have to rebuild from source I would prefer to just simply resign the package, by running the following commands (similar to what I'm now doing for jellyfin for tizen 8 as well)

```
tizen package --type wgt --sign MyCert -- D:\Downloads\TizenBrewStandalone-New.wgt
tizen install -n D:\Downloads\TizenBrewStandalone-New.wgt -t MYSAMSUNGID
```

Thanks!

**Comment by reisxd** [comment]
You can do the same with the current "old" package, the difference between them are just certificates.
