### ISSUE TITLE
Tizen 8.0 can't be installed anymore?

### ISSUE THREAD

**Issue by Matthew-MBG** [reisxd/TizenBrew#79]
![image](https://github.com/user-attachments/assets/e2ec23d5-5365-4bac-b46a-843af9357b79)

**Comment by Matthew-MBG** [comment]
Issue was that this wasn't installed.
![image](https://github.com/user-attachments/assets/cb44471e-525d-405f-8708-42f4a7586350)

**Comment by Matthew-MBG** [comment]
Never mind, still not working

**Comment by testuser7** [comment]
You can manually generate certificates and then sign package: https://gist.github.com/andreas-mausch/026413d908ba61cda15981bb4fbcd276
