### ISSUE TITLE
module stop working or not showing in the app

### ISSUE THREAD

**Issue by ansh5671** [reisxd/TizenBrew#8]
@foxreis/tizentube is not showing in the app anymore.
![20240412_220555](https://github.com/reisxd/TizenBrew/assets/52147088/f3d8b071-70eb-4616-a2f4-87194528f249)

**Comment by reisxd** [comment]
Try the latest release. If it still doesn't load the modules, you may have JSDelivr blocked.

Cannot reproduce.

**Comment by IntelCorei5-8350u** [comment]
> JSDelivr blocked

Problem happened today again. cdn.jsdeliver.net 's SSL has expired.
