### ISSUE TITLE
install failed[118, -12]

### ISSUE THREAD

**Issue by kevin3zk** [reisxd/TizenBrew#82]
After updating to the new UI of Samsung Q60C. The update uninstalled TizenBrew and I started getting this error `!
Could not install app. Reason: app_id[xvvl3S1bvH.TizenBrewStandalone] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [773]ms` after trying to install it.

**Comment by kevin3zk** [comment]
My TV is Tizen OS 7 but ill check it out.

**Comment by Matthew-MBG** [comment]
> My TV is Tizen OS 7 but ill check it out.

OneUI TV has Tizen 8.0 bases though.
