### ISSUE TITLE
Failed to install - Parsing Error

### ISSUE THREAD

**Issue by PottiMc** [reisxd/TizenBrew#87]
Hi, 
I am trying to get TizenBrew to work on my GQ55QN85.
Tizen Version 2013, 8.0.

Connection is possible without any problems, building the code is also possible without problems. Creating the package is also working fine. Samsung certificate is created and set as active.

When installing I get the following error:

Platform log view
--------------------
install xvvl3S1bvH.TizenBrewStandalone
package_path /home/owner/share/tmp/sdk_tools/tmp/TizenBrewStandalone.wgt
app_id[xvvl3S1bvH.TizenBrewStandalone] install start
app_id[xvvl3S1bvH.TizenBrewStandalone] install failed[118, -19], reason: Parsing error :
spend time for wascmd is [8147]ms
Failed to install Tizen application.
Total time: 00:00:13.020

The time in "Spend time for wascmd is varying, sometimes it is only 500ms, sometimes it takes 5000ms until it fails.

**Comment by reisxd** [comment]
Cannot reproduce.
