### ISSUE TITLE
Problem with TizenBrew Rebuilding

### ISSUE THREAD

**Issue by XCJ775** [reisxd/TizenBrew#93]
I am trying to rebuild TizenBrew. I got to step 2 and then encountered a problem in the terminal which reads: 

"npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported"

**Comment by reisxd** [comment]
These are not a problem. They're simply a deprecation warning (TizenBrew uses modules that are old to be compatible with ancient versions of Node).

**Comment by XCJ775** [comment]
OK but on the next step "sdb connect <TV IP>" it says "The syntax of the command is incorrect."

**Comment by XCJ775** [comment]
> 

OK but now I have a problem on step 5 of rebuilding TizenBrew. I typed "sdb connect TV IP", replacing TV IP for the IP address but it says "The syntax of the command is incorrect." I also tried without the arrows and it says "'sdb' is not recognized as an internal or external command, operable program or batch file."
