### ISSUE TITLE
Failed to install Tizen Application 

### ISSUE THREAD

**Issue by XCJ775** [reisxd/TizenBrew#95]
I don't know if I am supposed to resign or rebuild tizenbrew if it's the first time setting it up. I've tried both and get the same error message: "install failed[118, -12], reason: Check certificate error : :Invalid file reference. An unsinged file was found.:<-5>".

**Comment by carnife-x** [comment]
Similar issue here, these are my logs:
 *@*-MacBook-Pro tools % */tizen-studio/tools/ide/bin/tizen install -n /****/tizen-studio/widget/signed/TizenBrewStandalone.wgt
Transferring the package...
Transferred the package: /****/tizen-studio/widget/signed/TizenBrewStandalone.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install xvvl3S1bvH.TizenBrewStandalone
package_path /home/owner/share/tmp/sdk_tools/tmp/TizenBrewStandalone.wgt
app_id[xvvl3S1bvH.TizenBrewStandalone] install start
app_id[xvvl3S1bvH.TizenBrewStandalone] installing[9]
app_id[xvvl3S1bvH.TizenBrewStandalone] installing[19]
app_id[xvvl3S1bvH.TizenBrewStandalone] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [2346]ms
Failed to install Tizen application.

**Comment by reisxd** [comment]
If your device is Tizen 7 or higher, resign the app.

**Comment by carnife-x** [comment]
I have resigned the app and still face this issue, similar to @XCJ775 who also tried to rebuild it.
