### ISSUE TITLE
Is it possible to install any apk on the TV with TizenBrew ?

### ISSUE THREAD

**Issue by SleepInfinity** [reisxd/TizenBrew#98]
I'm wondering if it is possible to install any apk on the samsung tv using TizenBrew ? like installing Yacine tv to watch football matches for example.

And if yes how can i create a package with this apk so i can install it on the tv ?

Thankyou

**Comment by reisxd** [comment]
You cannot install APKs. Tizen is not Android. Also, not related to TizenBrew.
